### DISCUSSION TITLE
Missing credentials endpoint in Tractus-X Identity Hub Configuration

### DISCUSSION THREAD

**Discussion by mohamedkhalilbeldi** [eclipse-tractusx/tractusx-identityhub#64] [Q&A] [answered]
Hi,

I'm setting up an MVD (Minimum Viable Data space) using the Tractus-X stack. While configuring the Tractus-X Identity Hub Helm chart values, I noticed that unlike the Identity Hub of Eclipse EDC, there is no explicit credentials endpoint configuration available.

Normally, the credentials endpoint is defined in the DID document under the CredentialService section. However, in the Tractus-X variant, this endpoint seems to be missing.

In the values.yaml file, I see the following configuration:

```
    credentials:
      # -- port for incoming api calls
      port: 8083
      # -- path for incoming api calls
      path: **/api/presentation**
```

This defines a "presentation" endpoint, which is normally used for the DCP presentation process — not for credentials.

So my questions are:

Is it correct to use the same presentation endpoint as the credentialsEndpoint in the DID document under the CredentialService section?

Why is there a credentialsEndpoint in the mxd tutorial at https://github.com/eclipse-tractusx/tutorial-resources/blob/main/mxd/modules/identity-hub/main.tf, while it seems to be missing in the default Tractus-X Identity Hub Helm chart configuration?

Thanks in advance for the clarification.
