### ISSUE TITLE
spec.rules[0].http.paths value is not set to ingress settings

### ISSUE THREAD

**Issue by saudkhan116** [eclipse-tractusx/tractusx-identityhub#83]
### Current Behavior

When enabling ingresses, there is an issue with the ingress configuration in helm templates. In templates/ingress.yaml file, the **spec.rules[0].http.paths** expects a value and the value is not populated. Please see the below screenshot for reference.

![Image](https://github.com/user-attachments/assets/35e05d5f-b6cc-4555-9286-7c6f3f0953ac)

In the below screenshot, the helm template command is used to check the value of **spec.rules[0].http.paths**.

![Image](https://github.com/user-attachments/assets/6379708a-aeb9-4998-a767-270efc6d20d5)

### Expected Behavior

The value of **spec.rules[0].http.paths** is expected to be set.

```yaml
...
spec:
  ...
  rules:
   - host: "ih-identity.arena2036-x.de"
   http
     paths:
     - path: /management
          pathType: Prefix
          backend:
            service:
              ...
...
```

### Steps To Reproduce

```bash
cd tractusx-identityhub/charts/tractusx-identityhub
helm dependency update .
# to install the helm chart in debug mode
helm install idh -n identityhub -f values.yaml --debug .
# to print the template values with installing the chart
helm template idh -n identityhub -f values.yaml --debug .
```
